#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"; IMAGE_SOURCE_TYPE="$2"; TMP_WORK_DIR="$3"; REV="$4"

# Current git rev is either master or 0{40} if this is the first push.
# Ideally we'd get this direct from the prereceive hook, but it's not passed
# through by dokku at the moment.
OLDREV=$(cat $DOKKU_ROOT/$APP/refs/heads/master 2>/dev/null ||
         echo 0000000000000000000000000000000000000000)

# If we're called as a result of a ps:rebuild or similar, then REV will be
# empty, in which case we should set it to the OLDREV.
if [[ -z "$REV" ]]; then
  NEWREV=$OLDREV
else
  NEWREV=$REV
fi

"$(dirname $0)"/trigger receive-app $APP \
    git_rev=$NEWREV \
    git_rev_before=$OLDREV
